key = ""
client_id = ""
client_secret = ""

appid = ""
secret = ""

rate_test_utl = ""

mql_url = "127.0.0.1"
mql_user = ""
mql_pswd = ""
mql_db = ""



info = [
	{'coin_short_name': 'ORS', 'coin_full_name': 'OriginSport', 'repo_name': 'OriginSport/bet-center'},
	{'coin_short_name': 'ZIL', 'coin_full_name': 'Zilliqa', 'repo_name': 'Zilliqa/Zilliqa'},
	{'coin_short_name': 'BTM', 'coin_full_name': 'Bytom', 'repo_name': 'Bytom/bytom'},
	{'coin_short_name': 'GNT', 'coin_full_name': 'Golem', 'repo_name': 'golemfactory/golem'},
	{'coin_short_name': 'BTCP', 'coin_full_name': 'Bitcoin Private', 'repo_name': 'BTCPrivate/BitcoinPrivate'},
	{'coin_short_name': 'BCD', 'coin_full_name': 'Bitcoin Diamond', 'repo_name': 'eveybcd/BitcoinDiamond'},
	{'coin_short_name': 'HSR', 'coin_full_name': 'Hshare', 'repo_name': 'HcashOrg/hcashd'},
	{'coin_short_name': 'PIVX', 'coin_full_name': 'PIVX', 'repo_name': 'PIVX-Project/PIVX'},
	{'coin_short_name': 'MOAC', 'coin_full_name': 'MOAC', 'repo_name': 'MOACChain/moac-core'},
	{'coin_short_name': 'MITH', 'coin_full_name': 'Mithril', 'repo_name': 'mithio/mithril-smart-contract'},
	{'coin_short_name': 'MYB', 'coin_full_name': 'MyBit Token', 'repo_name': 'MyBitFoundation/MyBitDapp'},
	{'coin_short_name': 'BFT', 'coin_full_name': 'BnkToTheFuture', 'repo_name': 'BankToTheFuture/bft'},
	{'coin_short_name': 'BIX', 'coin_full_name': 'Bibox Token', 'repo_name': 'bibox365/bixtoken'},
	{'coin_short_name': 'GBYTE', 'coin_full_name': 'Byteball Bytes', 'repo_name': 'byteball/byteball'},
	{'coin_short_name': 'STQ', 'coin_full_name': 'Storiqa', 'repo_name': 'Storiqa/ico_smart_contract'},
	{'coin_short_name': 'NEXO', 'coin_full_name': 'Nexo', 'repo_name': 'nexofinance/NEXO-Token'},
	{'coin_short_name': 'BTCD', 'coin_full_name': 'BitcoinDark', 'repo_name': 'jl777/btcd'},
	{'coin_short_name': 'TNB', 'coin_full_name': 'Time New Bank', 'repo_name': 'fanxiong/crowdsale-contracts'},
	{'coin_short_name': 'SMART', 'coin_full_name': 'SmartCash', 'repo_name': 'SmartCash/smartcash'},
	{'coin_short_name': 'ENJ', 'coin_full_name': 'Enjin Coin', 'repo_name': 'enjin/contracts'},
	{'coin_short_name': 'VTC', 'coin_full_name': 'Vertcoin', 'repo_name': 'vertcoin/vertcoin'},
	{'coin_short_name': 'VEE', 'coin_full_name': 'BLOCKv', 'repo_name': 'BLOCKvIO/documentation'},
	{'coin_short_name': 'BOS', 'coin_full_name': 'BOScoin', 'repo_name': 'owlchain/owlchain-core'},
	{'coin_short_name': 'RDN', 'coin_full_name': 'Raiden Network Token', 'repo_name': 'raiden-network/raiden'},
	{'coin_short_name': 'UBQ', 'coin_full_name': 'Ubiq', 'repo_name': 'ubiq/go-ubiq'},
	{'coin_short_name': 'ZCL', 'coin_full_name': 'ZClassic', 'repo_name': 'z-classic/zclassic'},


	{'coin_short_name': 'XPM', 'coin_full_name': 'Primecoin', 'repo_name': 'primecoin/primecoin'},
	{'coin_short_name': 'RKT', 'coin_full_name': 'Rock', 'repo_name': 'Gibraltar-Blockchain-Exchange/rock-token'},
	{'coin_short_name': 'BTX', 'coin_full_name': 'Bitcore', 'repo_name': 'LIMXTEC/BitCore'},
	{'coin_short_name': 'CLOAK', 'coin_full_name': 'CloakCoin', 'repo_name': 'CloakProject/Cloak2Public'},
	{'coin_short_name': 'SLS', 'coin_full_name': 'SaluS', 'repo_name': 'saluscoin/SaluS'},
	{'coin_short_name': 'RCN', 'coin_full_name': 'Ripio Credit Network', 'repo_name': 'ripio/rcn-network'},
	{'coin_short_name': 'EMC2', 'coin_full_name': 'Einsteinium', 'repo_name': 'emc2foundation/einsteinium'},
	{'coin_short_name': 'XP', 'coin_full_name': 'Experience Points', 'repo_name': 'eXperiencePoints/XPCoin'},
	{'coin_short_name': 'VIA', 'coin_full_name': 'Viacoin', 'repo_name': 'viacoin/viacoin'},
	{'coin_short_name': 'WPR', 'coin_full_name': 'WePower', 'repo_name': 'WePowerNetwork/wepower-contracts'},
	{'coin_short_name': 'RVN', 'coin_full_name': 'Ravencoin', 'repo_name': 'RavenProject/Ravencoin'},
	{'coin_short_name': 'MNX', 'coin_full_name': 'MinexCoin', 'repo_name': 'minexcoin/minexcoin'},
	{'coin_short_name': 'ION', 'coin_full_name': 'ION', 'repo_name': 'ionomy/ion'},
	{'coin_short_name': 'VIBE', 'coin_full_name': 'VIBE', 'repo_name': 'amack2u/VibeHub'},
	{'coin_short_name': 'XSN', 'coin_full_name': 'Stakenet', 'repo_name': 'X9Developers/XSN'},
	{'coin_short_name': 'ZOI', 'coin_full_name': 'Zoin', 'repo_name': 'zoinofficial/zoin'},
	{'coin_short_name': 'FAIR', 'coin_full_name': 'FairCoin', 'repo_name': 'FairCoinTeam/fair-coin'},
	{'coin_short_name': 'UNO', 'coin_full_name': 'Unobtanium', 'repo_name': 'unobtanium-official/Unobtanium'},
	{'coin_short_name': 'AEON', 'coin_full_name': 'Aeon', 'repo_name': 'aeonix/aeon'},
	{'coin_short_name': 'PHR', 'coin_full_name': 'Phore', 'repo_name': 'phoreproject/Phore'},
	{'coin_short_name': 'FTC', 'coin_full_name': 'Feathercoin', 'repo_name': 'FeatherCoin/Feathercoin'},
	{'coin_short_name': 'ODE', 'coin_full_name': 'ODEM', 'repo_name': 'odemio/ico'},
	{'coin_short_name': 'SBD', 'coin_full_name': 'Steem Dollars', 'repo_name': 'steemit/steem'},
	{'coin_short_name': 'COB', 'coin_full_name': 'Cobinhood', 'repo_name': 'cobinhood/cobinhood-api-public'},
	{'coin_short_name': 'XEL', 'coin_full_name': 'Elastic', 'repo_name': 'sprocket-fpga/xel_miner'},
	{'coin_short_name': 'UUU', 'coin_full_name': 'U Network', 'repo_name': 'U-Network/unetwork'},
	{'coin_short_name': 'CSC', 'coin_full_name': 'CasinoCoin', 'repo_name': 'casinocoin/casinocoin'},
	{'coin_short_name': 'BLT', 'coin_full_name': 'Bloom', 'repo_name': 'hellobloom/core'},
	{'coin_short_name': 'COLX', 'coin_full_name': 'ColossusXT', 'repo_name': 'ColossusCoinXT/ColossusCoinXT'},
	{'coin_short_name': 'ONION', 'coin_full_name': 'DeepOnion', 'repo_name': 'deeponion/deeponion'},
	{'coin_short_name': 'STX', 'coin_full_name': 'Stox', 'repo_name': 'stx-technologies/stox-token'},
	{'coin_short_name': 'HST', 'coin_full_name': 'Decision Token', 'repo_name': 'HorizonState/token-sale'},
	{'coin_short_name': 'DMT', 'coin_full_name': 'DMarket', 'repo_name': 'suntechsoft/dmarket-smartcontract'},
	{'coin_short_name': 'BITG', 'coin_full_name': 'Bitcoin Green', 'repo_name': 'bitcoingreen/bitcoingreen'},
	{'coin_short_name': 'PZM', 'coin_full_name': 'PRIZM', 'repo_name': 'prizmspace/PrizmCore'},
	{'coin_short_name': 'LEO', 'coin_full_name': 'LEOcoin', 'repo_name': 'Leocoin-project/LEOcoin'},
	{'coin_short_name': 'BITB', 'coin_full_name': 'Bean Cash', 'repo_name': 'TeamBitBean/bitbean-core'},
	{'coin_short_name': 'CRW', 'coin_full_name': 'Crown', 'repo_name': 'Crowndev/crowncoin'},
	{'coin_short_name': 'PASC', 'coin_full_name': 'Pascal Coin', 'repo_name': 'PascalCoin/PascalCoin'},
	{'coin_short_name': 'HXX', 'coin_full_name': 'Hexx', 'repo_name': 'hexxcointakeover/hexxcoin'},
	{'coin_short_name': 'ARN', 'coin_full_name': 'Aeron', 'repo_name': 'aeronaero/aeron'},
	{'coin_short_name': 'LINDA', 'coin_full_name': 'Linda', 'repo_name': 'Lindacoin/Linda'},
	{'coin_short_name': 'IOC', 'coin_full_name': 'I/O Coin', 'repo_name': 'IOCoin/DIONS'},
	{'coin_short_name': 'GRC', 'coin_full_name': 'GridCoin', 'repo_name': 'gridcoin/Gridcoin-Research'},
	{'coin_short_name': 'BBR', 'coin_full_name': 'Boolberry', 'repo_name': 'cryptozoidberg/boolberry'},
	{'coin_short_name': 'ALQO', 'coin_full_name': 'ALQO', 'repo_name': 'alqocrypto/alqo'},
	{'coin_short_name': 'DEV', 'coin_full_name': 'DeviantCoin', 'repo_name': 'Deviantcoin/Source'},
	{'coin_short_name': 'CHP', 'coin_full_name': 'CoinPoker', 'repo_name': 'CoinPokerOfficial/ico-smartcontracts'},
	{'coin_short_name': 'DMD', 'coin_full_name': 'Diamond', 'repo_name': 'DMDcoin/Diamond'},
	{'coin_short_name': 'BIS', 'coin_full_name': 'Bismuth', 'repo_name': 'hclivess/Bismuth'},
	{'coin_short_name': 'RADS', 'coin_full_name': 'Radium', 'repo_name': 'RadiumCore/radium-0.11'},
	{'coin_short_name': 'EKO', 'coin_full_name': 'EchoLink', 'repo_name': 'EchoLinkTech/Echo'},
	{'coin_short_name': 'MWAT', 'coin_full_name': 'Restart Energy MWAT', 'repo_name': 'TransylvaniaHighTech/RestartEnergyICO'},
	{'coin_short_name': 'FLO', 'coin_full_name': 'FlorinCoin', 'repo_name': 'floblockchain/flo'},
	{'coin_short_name': 'LA', 'coin_full_name': 'LATOKEN', 'repo_name': 'ElKornacio/contracts-early'},
	{'coin_short_name': 'HYDRO', 'coin_full_name': 'Hydrogen', 'repo_name': 'hydrogen-dev/smart-contract'},
	{'coin_short_name': 'LUX', 'coin_full_name': 'LUXCoin', 'repo_name': '216k155/lux'},
	{'coin_short_name': 'SLR', 'coin_full_name': 'SolarCoin', 'repo_name': 'onsightit/solarcoin'},
	{'coin_short_name': 'SIB', 'coin_full_name': 'SIBCoin', 'repo_name': 'ivansib/sibcoin'},
	{'coin_short_name': 'RBY', 'coin_full_name': 'Rubycoin', 'repo_name': 'rubycoinorg/rubycoin'},
	{'coin_short_name': 'POLIS', 'coin_full_name': 'Polis', 'repo_name': 'polispay/polis'},
	{'coin_short_name': 'SHND', 'coin_full_name': 'StrongHands', 'repo_name': 'stronghands/stronghands'},
	{'coin_short_name': 'VRC', 'coin_full_name': 'VeriCoin', 'repo_name': 'vericoin/vericoin'},
	{'coin_short_name': 'PRG', 'coin_full_name': 'Paragon', 'repo_name': 'paragon-coin/token'},
	{'coin_short_name': 'PKT', 'coin_full_name': 'Playkey', 'repo_name': 'Playkey/ico-contracts'},
	{'coin_short_name': 'SLT', 'coin_full_name': 'Smartlands', 'repo_name': 'Smartlands-Platform/SLT'},
	{'coin_short_name': 'BSD', 'coin_full_name': 'BitSend', 'repo_name': 'LIMXTEC/BitSend'},
	{'coin_short_name': 'GCR', 'coin_full_name': 'Global Currency Reserve', 'repo_name': 'globalcurrencyreserve/gcr'},
	{'coin_short_name': 'CLAM', 'coin_full_name': 'Clams', 'repo_name': 'dooglus/bitaddress.org'},
	{'coin_short_name': 'XMY', 'coin_full_name': 'Myriad', 'repo_name': 'myriadteam/myriadcoin'},
	{'coin_short_name': 'DBIX', 'coin_full_name': 'DubaiCoin', 'repo_name': 'dubaicoin-dbix/go-dubaicoin'},
	{'coin_short_name': 'HWC', 'coin_full_name': 'HollyWoodCoin', 'repo_name': 'hollywoodcoin-project/HollyWoodCoin'},
	{'coin_short_name': 'OK', 'coin_full_name': 'OKCash', 'repo_name': 'okcashpro/okcash'},
	{'coin_short_name': 'SPRTS', 'coin_full_name': 'Sprouts', 'repo_name': 'SproutsCommunityRep/sprouts'},
	{'coin_short_name': 'SPD', 'coin_full_name': 'Stipend', 'repo_name': 'Stipend-Developer/stipend'},
	{'coin_short_name': 'COFI', 'coin_full_name': 'CoinFi', 'repo_name': 'coinfi/coinfi'},
	{'coin_short_name': 'ENRG', 'coin_full_name': 'Energycoin', 'repo_name': 'EnergyCoinProject/energycoin'},
	{'coin_short_name': 'DERO', 'coin_full_name': 'Dero', 'repo_name': 'deroproject/derosuite'},
	{'coin_short_name': 'GAM', 'coin_full_name': 'Gambit', 'repo_name': 'collincrypto/gambitcrypto'},
	{'coin_short_name': 'PND', 'coin_full_name': 'Pandacoin', 'repo_name': 'DigitalPandacoin/pandacoin'},
	{'coin_short_name': 'XST', 'coin_full_name': 'Stealth', 'repo_name': 'StealthSend/Stealth'},
	{'coin_short_name': 'NVC', 'coin_full_name': 'Novacoin', 'repo_name': 'novacoin-project/novacoin'},
	{'coin_short_name': 'PINK', 'coin_full_name': 'PinkCoin', 'repo_name': 'Pink2Dev/Pink2'},
	{'coin_short_name': 'DOVU', 'coin_full_name': 'Dovu', 'repo_name': 'TokenMarketNet/ico'},
	{'coin_short_name': 'TOA', 'coin_full_name': 'ToaCoin', 'repo_name': 'toacoin/TOA'},
	{'coin_short_name': 'MLM', 'coin_full_name': 'MktCoin', 'repo_name': 'Mktcoin-official/Mktcoin'},
	{'coin_short_name': 'XNK', 'coin_full_name': 'Ink Protocol', 'repo_name': 'InkProtocol/ink-protocol'},
	{'coin_short_name': 'SPHR', 'coin_full_name': 'Sphere', 'repo_name': 'SphereDevs/sphere'},
	{'coin_short_name': 'CURE', 'coin_full_name': 'Curecoin', 'repo_name': 'cygnusxi/CurecoinSource'},
	{'coin_short_name': 'XAUR', 'coin_full_name': 'Xaurum', 'repo_name': 'XaurumTeam/XaurumOnEthereum'},
	{'coin_short_name': 'XSPEC', 'coin_full_name': 'Spectrecoin', 'repo_name': 'spectrecoin/spectre'},
	{'coin_short_name': 'XHV', 'coin_full_name': 'Haven Protocol', 'repo_name': 'havenprotocol/haven'},
	{'coin_short_name': 'XLR', 'coin_full_name': 'Solaris', 'repo_name': 'Solaris-Project/Solaris'},
	{'coin_short_name': 'TX', 'coin_full_name': 'TransferCoin', 'repo_name': 'transferdev/Transfercoin'},
	{'coin_short_name': 'TIPS', 'coin_full_name': 'FedoraCoin', 'repo_name': 'fedoracoin-dev/fedoracoin'},
	{'coin_short_name': 'GCC', 'coin_full_name': 'Global Cryptocurrency', 'repo_name': 'TheGCCcoin/TheGCCcoin-source-code'},
	{'coin_short_name': 'AUR', 'coin_full_name': 'Auroracoin', 'repo_name': 'aurarad/auroracoin'},
	{'coin_short_name': 'VIT', 'coin_full_name': 'Vice Industry Token', 'repo_name': 'ViceIndustryToken/'},
	{'coin_short_name': 'KORE', 'coin_full_name': 'Kore', 'repo_name': 'Kore-Core/kore'},
	{'coin_short_name': 'ESP', 'coin_full_name': 'Espers', 'repo_name': 'cryptocoderz/espers'},
	{'coin_short_name': 'GBX', 'coin_full_name': 'GoByte', 'repo_name': 'gobytecoin/gobyte'},
	{'coin_short_name': 'ERC', 'coin_full_name': 'EuropeCoin', 'repo_name': 'LIMXTEC/Europecoin-V3'},
	{'coin_short_name': 'HYP', 'coin_full_name': 'HyperStake', 'repo_name': 'hyperstake/HyperStake'},
	{'coin_short_name': 'OPT', 'coin_full_name': 'Opus', 'repo_name': 'Opus-foundation/contracts'},
	{'coin_short_name': 'PURE', 'coin_full_name': 'Pure', 'repo_name': 'puredev321/pure'},
	{'coin_short_name': 'DNR', 'coin_full_name': 'Denarius', 'repo_name': 'carsenk/denarius'},
	{'coin_short_name': 'NLX', 'coin_full_name': 'Nullex', 'repo_name': 'white92d15b7/GPU-Coin'},
	{'coin_short_name': 'PCL', 'coin_full_name': 'Peculium', 'repo_name': 'PeculiumPCL/Peculium'},
	{'coin_short_name': 'ANC', 'coin_full_name': 'Anoncoin', 'repo_name': 'Anoncoin/anoncoin'},
	{'coin_short_name': 'KB3', 'coin_full_name': 'B3Coin', 'repo_name': 'B3-Coin/B3-CoinV2'},
	{'coin_short_name': 'BTCZ', 'coin_full_name': 'BitcoinZ', 'repo_name': 'bitcoinz-pod/bitcoinz'},
	{'coin_short_name': 'MEME', 'coin_full_name': 'Memetic / PepeCoin', 'repo_name': 'pepeteam/pepecoin'},
	{'coin_short_name': 'MONK', 'coin_full_name': 'Monkey Project', 'repo_name': 'MONKEYPROJECT/Monkey'},
	{'coin_short_name': 'EXCL', 'coin_full_name': 'ExclusiveCoin', 'repo_name': 'exclfork/ExclusiveCoin'},
	{'coin_short_name': 'CRAVE', 'coin_full_name': 'Crave', 'repo_name': 'Crave-Project/Crave-NG'},
	{'coin_short_name': 'UNIT', 'coin_full_name': 'Universal Currency', 'repo_name': 'unitcurrency/unitcurrency'},
	{'coin_short_name': 'NTRN', 'coin_full_name': 'Neutron', 'repo_name': 'neutroncoin/neutron'},
	{'coin_short_name': 'KRB', 'coin_full_name': 'Karbo', 'repo_name': 'seredat/karbowanec'},
	{'coin_short_name': 'EBST', 'coin_full_name': 'eBoost', 'repo_name': 'eBoostCrypto/eBoost'},
	{'coin_short_name': 'XHI', 'coin_full_name': 'HiCoin', 'repo_name': 'hicoindev/hicoin'},
	{'coin_short_name': 'SPR', 'coin_full_name': 'SpreadCoin', 'repo_name': 'spreadcoin/spreadcoin'},
	{'coin_short_name': 'VZT', 'coin_full_name': 'Vezt', 'repo_name': 'Vezt/Vezt'},
	{'coin_short_name': 'ORE', 'coin_full_name': 'Galactrum', 'repo_name': 'galactrum/galactrum'},
	{'coin_short_name': 'SUMO', 'coin_full_name': 'Sumokoin', 'repo_name': 'sumoprojects/sumokoin'},
	{'coin_short_name': 'RIC', 'coin_full_name': 'Riecoin', 'repo_name': 'riecoin/riecoin'},
	{'coin_short_name': 'HOLD', 'coin_full_name': 'Interstellar Holdings', 'repo_name': 'InterstellarHoldings/InterstellarHoldings'},
	{'coin_short_name': 'ZEIT', 'coin_full_name': 'Zeitcoin', 'repo_name': 'zeitcoin/zeitcoin'},
	{'coin_short_name': 'BUZZ', 'coin_full_name': 'BuzzCoin', 'repo_name': 'buzzcoin-project/BUZZ'},
	{'coin_short_name': 'MSR', 'coin_full_name': 'Masari', 'repo_name': 'masari-project/masari'},
	{'coin_short_name': 'BLU', 'coin_full_name': 'BlueCoin', 'repo_name': 'bluecoiner/bluecoin-new'},
	{'coin_short_name': 'CPY', 'coin_full_name': 'COPYTRACK', 'repo_name': 'copytrackio/cpy-contracts'},
	{'coin_short_name': 'CMPCO', 'coin_full_name': 'CampusCoin', 'repo_name': 'campuscoindev/CampusCoin-Source'},
	{'coin_short_name': 'CANN', 'coin_full_name': 'CannabisCoin', 'repo_name': 'cannabiscoindev/cannabiscoin420'},
	{'coin_short_name': 'SXC', 'coin_full_name': 'Sexcoin', 'repo_name': 'sexcoin-project/sexcoin'},
	{'coin_short_name': 'UFO', 'coin_full_name': 'Uniform Fiscal Object', 'repo_name': 'fiscalobject/ufo'},
	{'coin_short_name': '1337', 'coin_full_name': 'Elite', 'repo_name': 'xenonflux/1337'},
	{'coin_short_name': 'JIYO', 'coin_full_name': 'Jiyo', 'repo_name': 'jiyocoin/jiyo-core'},
	{'coin_short_name': 'EGC', 'coin_full_name': 'EverGreenCoin', 'repo_name': 'EverGreenCoinDev/EverGreenCoin'},
	{'coin_short_name': 'XGOX', 'coin_full_name': 'XGOX', 'repo_name': 'bumbacoin/xgox'},
	{'coin_short_name': 'RUP', 'coin_full_name': 'Rupee', 'repo_name': 'rupeedigitalassets/RUPEE'},
	{'coin_short_name': 'PHO', 'coin_full_name': 'Photon', 'repo_name': 'photonproject/photon'},
	{'coin_short_name': 'BBP', 'coin_full_name': 'BiblePay', 'repo_name': 'biblepay/biblepay'},


    {'coin_short_name': 'ICX', 'coin_full_name': 'ICON', 'repo_name': 'theloopkr/loopchain'},
	{'coin_short_name': 'TRX', 'coin_full_name': 'TRON', 'repo_name': 'tronprotocol/java-tron'},
	{'coin_short_name': 'NEM', 'coin_full_name': 'NEM', 'repo_name': 'NemProject/nem.core'},
	{'coin_short_name': 'MIOTA', 'coin_full_name': 'IOTA', 'repo_name': 'iotaledger/wallet'},
	{'coin_short_name': 'ETC', 'coin_full_name': 'Ethereum Classic', 'repo_name': 'ethereumproject/go-ethereum'},
	{'coin_short_name': 'PPT', 'coin_full_name': 'Populous', 'repo_name': 'bitpopulous/populous-smartcontracts'},
	{'coin_short_name': 'SNT', 'coin_full_name': 'Status', 'repo_name': 'status-im/status-react'},
	{'coin_short_name': 'STRAT', 'coin_full_name': 'Stratis', 'repo_name': 'stratisproject/StratisBitcoinFullNode'},
	{'coin_short_name': 'AE', 'coin_full_name': 'Aeternity', 'repo_name': 'aeternity/epoch'},
	{'coin_short_name': 'STORM', 'coin_full_name': 'Storm', 'repo_name': 'StormX-Inc/crowdsale'},
	{'coin_short_name': 'NULS', 'coin_full_name': 'Nuls', 'repo_name': 'nuls-io/nuls'},
	{'coin_short_name': 'ENG', 'coin_full_name': 'Enigma', 'repo_name': 'enigmampc/catalyst'},
	{'coin_short_name': 'DRGN', 'coin_full_name': 'Dragonchain', 'repo_name': 'dragonchain/dragonchain'},
	{'coin_short_name': 'SYS', 'coin_full_name': 'Syscoin', 'repo_name': 'syscoin/syscoin'},
	{'coin_short_name': 'GXS', 'coin_full_name': 'GXChain', 'repo_name': 'gxchain/gxb-core'},
	{'coin_short_name': 'SKY', 'coin_full_name': 'Skycoin', 'repo_name': 'skycoin/skycoin'},
	{'coin_short_name': 'RDD', 'coin_full_name': 'ReddCoin', 'repo_name': 'reddcoin-project/reddcoin'},
	{'coin_short_name': 'MONA', 'coin_full_name': 'MonaCoin', 'repo_name': 'monacoinproject/monacoin'},
	{'coin_short_name': 'BNT', 'coin_full_name': 'Bancor', 'repo_name': 'bancorprotocol/contracts'},
	{'coin_short_name': 'FSN', 'coin_full_name': 'Fusion', 'repo_name': 'FUSIONFoundation/TokenSale'},
	{'coin_short_name': 'ELA', 'coin_full_name': 'Elastos', 'repo_name': 'elastos/Elastos.OS'},
	{'coin_short_name': 'XZC', 'coin_full_name': 'ZCoin', 'repo_name': 'zcoinofficial/zcoin'},
	{'coin_short_name': 'NEBL', 'coin_full_name': 'Neblio', 'repo_name': 'NeblioTeam/neblio'},
	{'coin_short_name': 'ACT', 'coin_full_name': 'Achain', 'repo_name': 'Achain-Dev/Achain'},
	{'coin_short_name': 'R', 'coin_full_name': 'Revain', 'repo_name': 'Revain/Token'},
	{'coin_short_name': 'HOT', 'coin_full_name': 'Holo', 'repo_name': 'holochain/holochain-proto'},
	{'coin_short_name': 'MANA', 'coin_full_name': 'Decentraland', 'repo_name': 'decentraland/marketplace'},
	{'coin_short_name': 'PART', 'coin_full_name': 'Particl', 'repo_name': 'particl/particl-desktop'},
	{'coin_short_name': 'EMC', 'coin_full_name': 'Emercoin', 'repo_name': 'emercoin/emercoin'},
	{'coin_short_name': 'STORJ', 'coin_full_name': 'Storj', 'repo_name': 'storj/storjshare-daemon'},
	{'coin_short_name': 'ZEN', 'coin_full_name': 'ZenCash', 'repo_name': 'ZencashOfficial/zen'},
	{'coin_short_name': 'NXS', 'coin_full_name': 'Nexus', 'repo_name': 'Nexusoft/Nexus'},
	{'coin_short_name': 'QSP', 'coin_full_name': 'Quantstamp', 'repo_name': 'quantstamp/mythril'},
	{'coin_short_name': 'CS', 'coin_full_name': 'Credits', 'repo_name': 'CREDITSCOM/API'},
	{'coin_short_name': 'RUFF', 'coin_full_name': 'Ruff', 'repo_name': 'RuffNotes/RuffChain'},
	{'coin_short_name': 'SMART', 'coin_full_name': 'SmartMesh', 'repo_name': 'SmartMeshFoundation/Spectrum'},
	{'coin_short_name': 'ABT', 'coin_full_name': 'Arcblock', 'repo_name': 'ArcBlock/Whitepaper'},
	{'coin_short_name': 'NEO', 'coin_full_name': 'NEO', 'repo_name': 'neo-project/neo'},
	{'coin_short_name': 'XLM', 'coin_full_name': 'Stellar', 'repo_name': 'stellar/stellar-core'},
	{'coin_short_name': 'DASH', 'coin_full_name': 'Dash', 'repo_name': 'dashpay/dash'},
	{'coin_short_name': 'LSK', 'coin_full_name': 'Lisk', 'repo_name': 'LiskHQ/lisk'},
	{'coin_short_name': 'QTUM', 'coin_full_name': 'Qtum', 'repo_name': 'qtumproject/qtum'},
	{'coin_short_name': 'XRB', 'coin_full_name': 'Nano', 'repo_name': 'clemahieu/raiblocks'},
	{'coin_short_name': 'ZEC', 'coin_full_name': 'Zcash', 'repo_name': 'zcash/zcash'},
	{'coin_short_name': 'STEEM', 'coin_full_name': 'Steem', 'repo_name': 'steemit/steem'},
	{'coin_short_name': 'BCN', 'coin_full_name': 'Bytecoin', 'repo_name': 'bcndev/bytecoin'},
	{'coin_short_name': 'XVG', 'coin_full_name': 'Verge', 'repo_name': 'vergecurrency/VERGE'},
	{'coin_short_name': 'SC', 'coin_full_name': 'Siacoin', 'repo_name': 'NebulousLabs/Sia'},
	{'coin_short_name': 'BTS', 'coin_full_name': 'BitShares', 'repo_name': 'bitshares/bitshares-core'},
	{'coin_short_name': 'DOGE', 'coin_full_name': 'Dogecoin', 'repo_name': 'dogecoin/dogecoin'},
	{'coin_short_name': 'BTC', 'coin_full_name': 'Bitcoin', 'repo_name': 'bitcoin/bitcoin'},
	{'coin_short_name': 'ETH', 'coin_full_name': 'Ethereum', 'repo_name': 'ethereum/go-ethereum'},
	{'coin_short_name': 'LTC', 'coin_full_name': 'Litecoin', 'repo_name': 'litecoin-project/litecoin'},
	{'coin_short_name': 'XMR', 'coin_full_name': 'Monero', 'repo_name': 'monero-project/monero'},
	{'coin_short_name': 'BTG', 'coin_full_name': 'Bitcoin Gold', 'repo_name': 'BTCGPU/BTCGPU'},
	{'coin_short_name': 'BCH', 'coin_full_name': 'Bitcoin Cash', 'repo_name': 'bitcoincashorg/spec'},
	{'coin_short_name': 'XRP', 'coin_full_name': 'Ripple', 'repo_name': 'ripple/rippled'},
	{'coin_short_name': 'EOS', 'coin_full_name': 'EOS', 'repo_name': 'EOSIO/eos'},
	{'coin_short_name': 'ADA', 'coin_full_name': 'Cardano', 'repo_name': 'input-output-hk/cardano-sl'},
	{'coin_short_name': 'OMG', 'coin_full_name': 'OmiseGO', 'repo_name': 'omise/omise-go'}
]
